version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  target-branch: "2.x"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: "2.x"
