language: java
sudo: false

jdk:
  - openjdk11
  - openjdk12
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk12
    - jdk: openjdk-ea

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)