ext {
    scalaVersion = '3.3.5'
    scalaCompiler = '3'
}

apply from: 'shared.gradle'
apply from: rootProject.file('gradle/benchmark-jmh.gradle')

sourceSets {
    main.scala.srcDirs += [file('src/main/scala-2.13+'), file('src/main/scala-3+')]
}

moduleConfig {
    moduleInfoPath = 'src/main/module-3/module-info.java'
}

spotless {
    scala {
        licenseHeaderFile rootProject.file('gradle/license.header'), 'package '
    }
}

tasks.withType(ScalaCompile).configureEach {
    scalaCompileOptions.with {
        deprecation = true
        encoding = 'UTF-8'
        additionalParameters = [
                '-project-url', projectUrl,
                '-explain',                             // Explain errors in more detail.
                '-explain-types',                       // Explain type errors in more detail.
                '-feature',                             // Emit warning and location for usages of features that should be imported explicitly.
                '-language:macros,implicitConversions',
                '-Wvalue-discard',                      // Emit warning and location when a result of a statement is unused.
                '-Wunused:nowarn,implicits,explicits,locals,params,privates',
                '-Xfatal-warnings',                     // Fail the compilation if there are any warnings.
                '-source:3.3',                          // Turn on future language features.
                '-java-output-version:8',
                '-P:wartremover:only-warn-traverser:org.wartremover.warts.Unsafe',
        ]
    }
}
