apply from: rootProject.file('gradle/benchmark-jmh.gradle')

description = 'Convenient utility to build JSON models by evaluating XPath expressions'

dependencies {
    api project(':xpath-to-xml-core')

    compileOnly libs.json.api

    testImplementation project(':xpath-to-xml-test')
    testImplementation libs.json.impl
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation libs.assertj
}
