[versions]
errorprone = '2.31.0'
jackson = '2.19.1'

[libraries]
assertj = 'org.assertj:assertj-core:3.27.3'
dom4j = 'org.dom4j:dom4j:2.1.4'
errorprone = { module = 'com.google.errorprone:error_prone_core', version.ref = 'errorprone' }
gson = 'com.google.code.gson:gson:2.13.1'
jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version.ref = 'jackson' }
jackson-dataformat-yaml = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml', version.ref = 'jackson' }
jaxen = 'jaxen:jaxen:2.0.0'
jdom2 = 'org.jdom:jdom2:2.0.6.1'
json = 'org.json:json:20250517'
json-api = 'jakarta.json:jakarta.json-api:2.1.3'
json-impl = 'org.glassfish:jakarta.json:2.0.1'
junit-bom = 'org.junit:junit-bom:5.13.2'
mockito = 'org.mockito:mockito-junit-jupiter:5.18.0'
scala-xml = 'org.scala-lang.modules:scala-xml_%%:2.4.0'
scalatest-funspec = 'org.scalatest:scalatest-funspec_%%:3.2.19'
scalatest-junit-runner = 'org.scalatestplus:junit-5-12_%%:3.2.19.0'
wartremover = 'org.wartremover:wartremover_%%:3.3.4'
xom = 'xom:xom:1.3.9'

[bundles]
scalatest = ["scalatest-funspec", "scalatest-junit-runner"]
