apply from: rootProject.file('gradle/benchmark-jmh.gradle')

description = 'Convenient utility to build XML models by evaluating XPath expressions'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    api project(':xpath-to-xml-core')

    implementation libs.dom4j

    testImplementation project(':xpath-to-xml-test')
    testImplementation libs.jaxen
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation libs.assertj
}

compileJava {
    options.release = 11
}
