name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    strategy:
      matrix:
        java: [ 11, 17 ]

    steps:
    - uses: actions/checkout@v3.0.0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.0.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: gradle
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v1
      with:
        arguments: build --no-daemon --scan
    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
