name: Build and Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: ⚙️ Run build
      run: ./gradlew build --no-daemon --scan
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/build/test-results/*/*.xml'
        require_tests: true
    - name: Create Test Summary
      uses: test-summary/action@v2
      with:
        paths: '**/build/test-results/*/*.xml'
      if: always()
    - name: Code Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
