name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: gradle
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --no-daemon --scan
    - name: Create test summary
      uses: test-summary/action@v2
      with:
        paths: '**/build/test-results/*/*.xml'
      if: always()
    - name: Code Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
