name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Release version'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Release with Gradle
        run: |
          echo "sonatypeUsername=$SONATYPE_USERNAME" >> gradle.properties
          echo "sonatypePassword=$SONATYPE_PASSWORD" >> gradle.properties
          ./gradlew release -Prelease.useAutomaticVersion=true
        env:
          GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
