name: Release
on:
  push:
    tags: ["**"]

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.repository == 'SimY4/xpath-to-xml'
      && !contains(toJSON(github.event.commits.*.message), '[skip release]')

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Release with Gradle
        run: |
          echo "sonatypeUsername=$SONATYPE_USERNAME" >> gradle.properties
          echo "sonatypePassword=$SONATYPE_PASSWORD" >> gradle.properties
          ./gradlew publish
        env:
          GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
